
version: '3.8'
services:
  nginx:
    image: nginx:stable
    container_name: nginx-web
    ports:
      - "8100:80"
    volumes:
      - ./src/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - node
      - mysql
    networks:
      - meweb-network

  mysql:
    image: mysql:latest
    container_name: mysql-web
    tty: true
    ports:
      - "3100:3306"
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meweb
      MYSQL_ROOT_PASSWORD: EjJmRYJgH7XwJWbu
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - meweb-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog-web
    ports:
      - 1100:1025
      - 8109:8025
    networks:
      - meweb-network

  node:
    image: node:16
    container_name: node-web
    tty: true
    command: npx tailwind-config-viewer
    ports:
      - 3101:3000
    volumes:
      - ./src/:/mnt
    working_dir: /mnt
    networks:
      - meweb-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web
    volumes:
      - ./src/:/var/www/html
    working_dir: /var/www/html
    networks:
      - meweb-network

networks:
  meweb-network: